Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.box_url = "ubuntu/trusty64"

    config.vm.define :"Spikes.SenecaJS"

    config.vm.synced_folder "../../SenecaJS", "/home/vagrant/code"

    config.vm.provider :virtualbox do |vb|
        vb.name = "Spikes.SenecaJS"
        vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    config.vm.provision :fabric do |fabric|
        fabric.fabfile_path = "../fabfile.py"
        fabric.tasks = ["scripts.ubuntu.update", "scripts.nodejs.install", "scripts.nodejs.tools.install", "scripts.ubuntu.cleanup_packages"]
    end
end